### ISSUE TITLE
To obtain public housing Data via API functions 

### ISSUE THREAD

**Issue by Kcube33** [TIC4901-Grp-6/REapplication#7]
- To test obtain data via POSTMAN
- Obtain the relevant information and fields
- Incorporate into PHP/HTML
- Store Data into internal SQL database
- Process Information to be reflected in website

**Comment by Kcube33** [comment]
API data successfully tested in PHP

**Comment by Kcube33** [comment]
Updated HDB Resale Quarter by Quarter Data. URA API data in progress

**Comment by Kcube33** [comment]
Updated wit URA APIs for 
Private Residential Property Transactions
Private Non-Landed Residential Properties Median Rentals by Name
Private Residential Properties Rental Contract
Private Residential Projects in the Pipeline

**Comment by vrhuvarkelvin** [comment]
HDB resale data pulled from HDB
